[connections.supabase]
SUPABASE_URL = "https://ugqhegbmwuyecujqqjte.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVncWhlZ2Jtd3V5ZWN1anFxanRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0NjI4NzYsImV4cCI6MjA3OTAzODg3Nn0.gBpEKduitjV_6naaWNmBmsVZtZt-Yftsos8h2SMsxFs"